spring.config.import: classpath:secrets.properties

server:
  port: 8082
  servlet:
    contextPath: /countdown-workout

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/narlock
    username: ${lmysql.username}
    password: ${lmysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
